
fcd: 
  url: https://fcd.terra.dev/v1

app:
  port: 9800
  database:
    name: "srv-contract"

database:
  mongodb:
    uri: mongodb://localhost:27017/
    name: srv-contract
    options: ""

  redis:
    host: "localhost"
    port: "6379"
    password: ""
