import { Currency } from "@trackterra/proto-schema/currency";

const stableCoins: Currency[] = [
    {
        name: "AUT",
        symbol: "uaud",
        decimals: 6,
        identifier: "uaud",
        icon: "",
    },
    {
        name: "CAT",
        symbol: "ucad",
        decimals: 6,
        identifier: "ucad",
        icon: "",
    },
    {
        name: "CHT",
        symbol: "uchf",
        decimals: 6,
        identifier: "uchf",
        icon: "",
    },
    {
        name: "CNT",
        symbol: "ucny",
        decimals: 6,
        identifier: "ucny",
        icon: "",
    },
    {
        name: "DKT",
        symbol: "udkk",
        decimals: 6,
        identifier: "udkk",
        icon: "",
    },
    {
        name: "EUT",
        symbol: "ueur",
        decimals: 6,
        identifier: "ueur",
        icon: "",
    },
    {
        name: "GBT",
        symbol: "ugbp",
        decimals: 6,
        identifier: "ugbp",
        icon: "",
    },
    {
        name: "HKT",
        symbol: "uhkd",
        decimals: 6,
        identifier: "uhkd",
        icon: "",
    },
    {
        name: "IDT",
        symbol: "uidr",
        decimals: 6,
        identifier: "uidr",
        icon: "",
    },
    {
        name: "INT",
        symbol: "uinr",
        decimals: 6,
        identifier: "uinr",
        icon: "",
    },
    {
        name: "JPT",
        symbol: "ujpy",
        decimals: 6,
        identifier: "ujpy",
        icon: "",
    },
    {
        name: "KRT",
        symbol: "ukrw",
        decimals: 6,
        identifier: "ukrw",
        icon: "",
    },
    {
        name: "LUNA",
        symbol: "uluna",
        decimals: 6,
        identifier: "uluna",
        icon: "",
    },
    {
        name: "MNT",
        symbol: "umnt",
        decimals: 6,
        identifier: "umnt",
        icon: "",
    },
    {
        name: "MYT",
        symbol: "umyr",
        decimals: 6,
        identifier: "umyr",
        icon: "",
    },
    {
        name: "NOT",
        symbol: "unok",
        decimals: 6,
        identifier: "unok",
        icon: "",
    },
    {
        name: "PHT",
        symbol: "uphp",
        decimals: 6,
        identifier: "uphp",
        icon: "",
    },
    {
        name: "SDT",
        symbol: "usdr",
        decimals: 6,
        identifier: "usdr",
        icon: "",
    },
    {
        name: "SET",
        symbol: "usek",
        decimals: 6,
        identifier: "usek",
        icon: "",
    },
    {
        name: "SGT",
        symbol: "usgd",
        decimals: 6,
        identifier: "usgd",
        icon: "",
    },
    {
        name: "THT",
        symbol: "uthb",
        decimals: 6,
        identifier: "uthb",
        icon: "",
    },
    {
        name: "TWT",
        symbol: "utwd",
        decimals: 6,
        identifier: "utwd",
        icon: "",
    },
    {
        name: "UST",
        symbol: "uusd",
        decimals: 6,
        identifier: "uusd",
        icon: "",
    },
];

export default stableCoins;