version: "3.2"

services:

  api-gateway:
    build:
      context: .
      dockerfile: server/api-gateway/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/api-gateway:${IMAGE_TAG:?err}"
    restart: always
    environment:
      - CONSUL_HOST=consul
      - DISCOVERY_HOST=api-gateway
    ports:
      - 2052:2052
    volumes:
      - storage-static:/nest/storage
      
  consul:
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    image: consul
    command: ["agent", "-server", "-bootstrap", "-ui", "-client", "0.0.0.0"]


  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017
  
  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379

volumes:
  storage-static: