version: "3.2"

services:
  api-gateway:
    build:
      context: .
      dockerfile: server/api-gateway/Dockerfile
      args:
        NODE_ENV: development
    image: "api-gateway:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 2052:2052
      - 4000:4000

  service-parser:
    build:
      context: .
      dockerfile: server/service-parser/Dockerfile
      args:
        NODE_ENV: development
    image: "service-parser:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50050:50050

  service-contract:
    build:
      context: .
      dockerfile: server/service-contract/Dockerfile
      args:
        NODE_ENV: development
    image: "service-contract:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50085:50085

  service-wallet:
    build:
      context: .
      dockerfile: server/service-wallet/Dockerfile
      args:
        NODE_ENV: development
    image: "service-wallet:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
    - 50075:50075
  
  consul:
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    image: consul
    command: ["agent", "-server", "-bootstrap", "-ui", "-client", "0.0.0.0"]
  eventstore:
    container_name: eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    # image: eventstore/eventstore:release-5.0.8
    image: ghcr.io/eventstore/eventstore:21.10.0-alpha-arm64v8

  nats:
    container_name: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    image: nats

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeit
    restart: always
    expose:
      - 27017

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379
