version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        NODE_ENV: development
    image: "trackterra/app:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - DISCOVERY_HOST=app
    ports:
      - 2052:2052
      - 4000:4000
    volumes:
      - storage-static:/nest/storage
  
  consul:
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    image: consul
    command: ["agent", "-server", "-bootstrap", "-ui", "-client", "0.0.0.0"]

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379

volumes:
  storage-static: