version: "3.2"

services:
  api-gateway:
    build:
      context: .
      dockerfile: server/api-gateway/Dockerfile
      args:
        NODE_ENV: development
    image: "trackterra/api-gateway:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=api-gateway
    ports:
      - 2052:2052
      - 4000:4000
    volumes:
      - storage-static:/nest/storage

  service-parser:
    build:
      context: .
      dockerfile: server/service-parser/Dockerfile
      args:
        NODE_ENV: development
    image: "trackterra/service-parser:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=service-parser
    ports:
      - 50050:50050
    volumes:
      - storage-static:/nest/storage

  service-contract:
    build:
      context: .
      dockerfile: server/service-contract/Dockerfile
      args:
        NODE_ENV: development
    image: "trackterra/service-contract:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=service-contract
    ports:
      - 50085:50085
    volumes:
      - storage-static:/nest/storage

  service-wallet:
    build:
      context: .
      dockerfile: server/service-wallet/Dockerfile
      args:
        NODE_ENV: development
    image: "trackterra/service-wallet:latest"
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=service-wallet
    ports:
      - 50075:50075
    volumes:
      - storage-static:/nest/storage
  
  consul:
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    image: consul
    command: ["agent", "-server", "-bootstrap", "-ui", "-client", "0.0.0.0"]

  nats:
    container_name: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    image: nats

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379

volumes:
  storage-static: