version: "3.2"

services:

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/app:${IMAGE_TAG:?err}"
    restart: always
    environment:
      - DISCOVERY_HOST=app
    ports:
      - 2052:2052
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - storage-static:/nest/storage
      
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017
  
  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379

volumes:
  storage-static: