version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        NODE_ENV: development
    image: "trackterra/app:latest"
    restart: always
    depends_on:
      - mongo
      - redis
    ports:
      - 2052:2052
      - 4000:4000
    env_file:
      - .env
    volumes:
      - storage-static:/nest/storage
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379

volumes:
  storage-static: