const stableCoins = [
  {
    name: 'AUT',
    symbol: 'AUT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uaud',
    icon: '',
    isStable: true,
  },
  {
    name: 'CAT',
    symbol: 'CAT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'ucad',
    icon: '',
    isStable: true,
  },
  {
    name: 'CHT',
    symbol: 'CHT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uchf',
    icon: '',
    isStable: true,
  },
  {
    name: 'CNT',
    symbol: 'CNT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'ucny',
    icon: '',
    isStable: true,
  },
  {
    name: 'DKT',
    symbol: 'DKT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'udkk',
    icon: '',
    isStable: true,
  },
  {
    name: 'EUT',
    symbol: 'EUT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'ueur',
    icon: '',
    isStable: true,
  },
  {
    name: 'GBT',
    symbol: 'GBT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'ugbp',
    icon: '',
    isStable: true,
  },
  {
    name: 'HKT',
    symbol: 'HKT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uhkd',
    icon: '',
    isStable: true,
  },
  {
    name: 'IDT',
    symbol: 'IDT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uidr',
    icon: '',
    isStable: true,
  },
  {
    name: 'INT',
    symbol: 'INT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uinr',
    icon: '',
    isStable: true,
  },
  {
    name: 'JPT',
    symbol: 'JPT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'ujpy',
    icon: '',
    isStable: true,
  },
  {
    name: 'KRT',
    symbol: 'KRT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'ukrw',
    icon: '',
    isStable: true,
  },
  {
    name: 'LUNA',
    symbol: 'LUNA',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uluna',
    icon: '',
    isStable: true,
  },
  {
    name: 'MNT',
    symbol: 'MNT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'umnt',
    icon: '',
    isStable: true,
  },
  {
    name: 'MYT',
    symbol: 'MYT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'umyr',
    icon: '',
    isStable: true,
  },
  {
    name: 'NOT',
    symbol: 'NOT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'unok',
    icon: '',
    isStable: true,
  },
  {
    name: 'PHT',
    symbol: 'PHT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uphp',
    icon: '',
    isStable: true,
  },
  {
    name: 'SDT',
    symbol: 'SDT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'usdr',
    icon: '',
    isStable: true,
  },
  {
    name: 'SET',
    symbol: 'SET',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'usek',
    icon: '',
    isStable: true,
  },
  {
    name: 'SGT',
    symbol: 'SGT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'usgd',
    icon: '',
    isStable: true,
  },
  {
    name: 'THT',
    symbol: 'THT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uthb',
    icon: '',
    isStable: true,
  },
  {
    name: 'TWT',
    symbol: 'TWT',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'utwd',
    icon: '',
    isStable: true,
  },
  {
    name: 'UST',
    symbol: 'UST',
    nullIndex: undefined,
    decimals: 6,
    identifier: 'uusd',
    icon: '',
    isStable: true,
  },
];

export default stableCoins;
