export const taxAppTitles = {
  regular: [
    { id: 'txhash', title: 'Tx hash' },
    { id: 'blockHeight', title: 'Block height' },
    { id: 'timestamp', title: 'Timestamp' },
    { id: 'label', title: 'Label' },
    { id: 'tag', title: 'Tag' },
    { id: 'contract', title: 'Contract' },
    { id: 'sender', title: 'Sender' },
    { id: 'recipient', title: 'Recipient' },
    { id: 'receivedAmount', title: 'Received amount' },
    { id: 'receivedToken', title: 'Received token' },
    { id: 'sentAmount', title: 'Sent amount' },
    { id: 'sentToken', title: 'Sent token' },
    { id: 'feeAmount', title: 'Fee amount' },
    { id: 'feeToken', title: 'Fee token' },
    { id: 'taxAmount', title: 'Tax amount' },
    { id: 'taxToken', title: 'Tax token' },
    { id: 'netWorthAmount', title: 'Networth amount' },
    { id: 'netWorthToken', title: 'Networth token' },
    { id: 'memo', title: 'Memo' },
    { id: 'friendlyDescription', title: 'Friendly description' },
  ],

  koinly: [
    { id: 'timestamp', title: 'Timestamp' },
    { id: 'sentAmount', title: 'Sent Amount' },
    { id: 'sentToken', title: 'Sent Currency' },
    { id: 'receivedAmount', title: 'Received Amount' },
    { id: 'receivedToken', title: 'Received Currency' },
    { id: 'feeAmount', title: 'Fee Amount' },
    { id: 'feeToken', title: 'Fee Currency' },
    { id: 'netWorthAmount', title: 'Networth Amount' },
    { id: 'netWorthToken', title: 'Networth Currency' },
    { id: 'label', title: 'Label' },
    { id: 'tag', title: 'Tag' },
    { id: 'friendlyDescription', title: 'Description' },
    { id: 'txhash', title: 'Tx hash' },
  ],

  cointracker: [
    { id: 'timestamp', title: 'Timestamp' },
    { id: 'receivedAmount', title: 'Received amount' },
    { id: 'receivedToken', title: 'Received token' },
    { id: 'sentAmount', title: 'Sent amount' },
    { id: 'sentToken', title: 'Sent token' },
    { id: 'feeAmount', title: 'Fee amount' },
    { id: 'feeToken', title: 'Fee token' },
    { id: 'label', title: 'Label' },
    { id: 'tag', title: 'Tag' },
  ]
};