database:
  app:
    port: 9800
    database:
      name: "srv-parser"

  mongodb:
    uri: mongodb://localhost:27017/
    name: srv-parser
    options: ""

  eventstore:
    poolMax:
    poolMin:
    streamProtocol: "http"
    hostname: "localhost"
    httpPort: 2113
    httpPotocol: "http"
    tcpPassword: "changeit"
    tcpUsername: "admin"
    tcpPort: 1113
    tcpProtocol: tcp

  redis:
    host: "localhost"
    port: "6379"
    password: ""
