fcd: 
  url: https://fcd.terra.dev/v1
  
app:
  port: 9750
  database:
    name: "srv-wallet"

database:
  mongodb:
    uri: mongodb://mongo:27017/
    name: srv-wallet
    options: ""

  eventstore:
    poolMax:
    poolMin:
    streamProtocol: "http"
    hostname: "eventstore"
    httpPort: 2113
    httpPotocol: "http"
    tcpPassword: "changeit"
    tcpUsername: "admin"
    tcpPort: 1113
    tcpProtocol: tcp

  redis:
    host: "redis"
    port: "6379"
    password: ""
