fcd: 
  url: https://fcd.terra.dev/v1
  
app:
  port: 9750
  database:
    name: "srv-wallet"

database:
  mongodb:
    uri: mongodb://localhost:27017/
    name: srv-wallet
    options: ""

  redis:
    host: "localhost"
    port: "6379"
    password: ""
