import { Currency } from "@trackterra/proto-schema/contract";

const stableCoins: Currency[] = [
    {
        name: "AUT",
        symbol: "AUT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uaud",
        icon: "",
    },
    {
        name: "CAT",
        symbol: "CAT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "ucad",
        icon: "",
    },
    {
        name: "CHT",
        symbol: "CHT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uchf",
        icon: "",
    },
    {
        name: "CNT",
        symbol: "CNT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "ucny",
        icon: "",
    },
    {
        name: "DKT",
        symbol: "DKT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "udkk",
        icon: "",
    },
    {
        name: "EUT",
        symbol: "EUT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "ueur",
        icon: "",
    },
    {
        name: "GBT",
        symbol: "GBT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "ugbp",
        icon: "",
    },
    {
        name: "HKT",
        symbol: "HKT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uhkd",
        icon: "",
    },
    {
        name: "IDT",
        symbol: "IDT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uidr",
        icon: "",
    },
    {
        name: "INT",
        symbol: "INT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uinr",
        icon: "",
    },
    {
        name: "JPT",
        symbol: "JPT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "ujpy",
        icon: "",
    },
    {
        name: "KRT",
        symbol: "KRT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "ukrw",
        icon: "",
    },
    {
        name: "LUNA",
        symbol: "LUNA",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uluna",
        icon: "",
    },
    {
        name: "MNT",
        symbol: "MNT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "umnt",
        icon: "",
    },
    {
        name: "MYT",
        symbol: "MYT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "umyr",
        icon: "",
    },
    {
        name: "NOT",
        symbol: "NOT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "unok",
        icon: "",
    },
    {
        name: "PHT",
        symbol: "PHT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uphp",
        icon: "",
    },
    {
        name: "SDT",
        symbol: "SDT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "usdr",
        icon: "",
    },
    {
        name: "SET",
        symbol: "SET",
        nullIndex: undefined,
        decimals: 6,
        identifier: "usek",
        icon: "",
    },
    {
        name: "SGT",
        symbol: "SGT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "usgd",
        icon: "",
    },
    {
        name: "THT",
        symbol: "THT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uthb",
        icon: "",
    },
    {
        name: "TWT",
        symbol: "TWT",
        nullIndex: undefined,
        decimals: 6,
        identifier: "utwd",
        icon: "",
    },
    {
        name: "UST",
        symbol: "UST",
        nullIndex: undefined,
        decimals: 6,
        identifier: "uusd",
        icon: "",
    },
];

export default stableCoins;