fcd: 
  url: https://fcd.terra.dev/v1
  
app:
  port: 9900
  caching:
    ttl: 5
    max: 1000

database:
  mongodb:
    uri: mongodb://localhost:27017/
    name: srv-account
    options: ""

  redis:
    host: "localhost"
    port: "6379"
    password: ""
