fcd: 
  url: https://fcd.terra.dev/v1
  
app:
  port: 9900
  caching:
    ttl: 5
    max: 1000

database:
  mongodb:
    uri: mongodb://mongo:27017/
    name: srv-account
    options: ""

  eventstore:
    poolMax:
    poolMin:
    streamProtocol: "http"
    hostname: "eventstore"
    httpPort: 2113
    httpPotocol: "http"
    tcpPassword: "changeit"
    tcpUsername: "admin"
    tcpPort: 1113
    tcpProtocol: tcp

  redis:
    host: "redis"
    port: "6379"
    password: ""
